version: "3.9"

services:
  api:
    build: ./backend
    container_name: fastapi_api
    ports:
      - "8001:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    volumes:
      - ./backend/app:/app/app
    restart: always

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 760396
      POSTGRES_DB: energie_ia
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
